
services:
  myapp:
    image: spring-boot-test:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wallet
      SPRING_DATASOURCE_USERNAME: afshin
      SPRING_DATASOURCE_PASSWORD: afshin
    networks:
      - ahs441

  mysql:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: afshin
      MYSQL_PASSWORD: afshin
      MYSQL_DATABASE: wallet
    ports:
      - "3306:3306"
    networks:
      - ahs441

networks:
  ahs441:
    driver: bridge