
server:
  port: 8080

logging:
  level:
    ir.ahs441 : info

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy
        jdbc:
          time_zone: UTC
        show_sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/wallet
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/master.xml
    contexts: master
    enabled: true
  application:
    name: wallet-service
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: swagger-ui.html
